version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: elsi_backend
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
