version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: elsi_backend
        ports:
            - "9000:8000"
        env_file:
            - .env.prod
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
